[build]
  command = "npm ci && npx prisma generate"
  functions = "netlify/functions"
  publish = "netlify/publish"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200