import { z } from 'zod';
import type { BusinessAnalysis, WebsiteGenerationContext } from './WebsiteStrategy';

/**
 * A deterministic creative layer placed before the LLM. It intentionally
 * describes visual decisions, never business facts, services or claims.
 */
export const visualArchetypes = [
  'luxury_real_estate', 'standard_real_estate', 'burger_restaurant', 'pizza_restaurant',
  'sushi_restaurant', 'premium_restaurant', 'acai_brand', 'solar_energy',
  'electronic_security', 'transport_logistics', 'veterinary', 'pet_store', 'beauty',
  'clinic', 'dentist', 'law_firm', 'accounting', 'construction', 'architecture',
  'automotive', 'gym', 'hotel', 'tourism', 'saas', 'consulting', 'industrial',
  'retail', 'generic_local_service',
] as const;
export type VisualArchetype = (typeof visualArchetypes)[number];

export const heroArchetypes = [
  'CINEMATIC_SPLIT', 'EDITORIAL_FULL_BLEED', 'PRODUCT_MONUMENT', 'TYPOGRAPHY_OVER_IMAGE',
  'GIANT_BRAND_WORD', 'FLOATING_DATA', 'ARCHITECTURAL_EDITORIAL', 'PRODUCT_CAMPAIGN',
  'DARK_TECH', 'ORGANIC_CARE', 'MAGAZINE_LAYOUT', 'LAYERED_COLLAGE',
  'MINIMAL_PRODUCT', 'ASYMMETRIC_SHOWCASE',
] as const;
export type HeroArchetype = (typeof heroArchetypes)[number];

const short = z.string().min(1).max(700);
export const artDirectionPlanSchema = z.object({
  version: z.literal('art-direction-v1'),
  seed: z.string().max(120),
  businessType: short,
  primaryArchetype: z.enum(visualArchetypes),
  secondaryArchetype: z.string().max(80),
  classificationSignals: z.array(z.string().max(120)).min(1).max(8),
  businessPositioning: short,
  targetAudience: short,
  visualPersonality: z.array(z.string().max(60)).min(3).max(6),
  visualKeywords: z.array(z.string().max(60)).min(4).max(10),
  primaryMood: z.string().max(80),
  secondaryMood: z.string().max(80),
  colorStrategy: z.object({ paletteFamily: short, contrast: z.string().max(120), accentUse: z.string().max(180) }),
  typographyStrategy: z.object({ display: z.string().max(120), body: z.string().max(120), scale: z.string().max(180), rationale: z.string().max(300) }),
  imageDirection: z.object({ subject: short, camera: short, lighting: short, composition: short, negativeSpace: short, palette: short, avoid: z.array(z.string().max(100)).min(3).max(10) }),
  hero: z.object({ archetype: z.enum(heroArchetypes), concept: short, composition: short, dominantElement: short, textPlacement: short, supportingElements: z.array(z.string().max(120)).max(5) }),
  contentHierarchy: z.array(z.string().max(180)).min(4).max(12),
  decorativeLanguage: short,
  sectionRhythm: short,
  interactionStyle: short,
  mobileStrategy: short,
  conversionStrategy: short,
  qualityTargets: z.object({ visualImpact: z.number().min(0).max(10), heroQuality: z.number().min(0).max(10), imageQuality: z.number().min(0).max(10), responsiveQuality: z.number().min(0).max(10) }),
});
export type ArtDirectionPlan = z.infer<typeof artDirectionPlanSchema>;

type Grammar = {
  secondary: string;
  personality: string[];
  keywords: string[];
  moods: [string, string];
  palettes: Array<[string, string, string]>;
  typography: Array<[string, string, string]>;
  heroes: HeroArchetype[];
  image: [string, string, string, string, string];
  composition: string;
  decorative: string;
  rhythm: string;
  interaction: string;
};

const grammars: Record<VisualArchetype, Grammar> = {
  luxury_real_estate: { secondary: 'premium_home', personality: ['calmo', 'arquitetônico', 'exclusivo'], keywords: ['cinematic', 'negative-space', 'quiet-luxury', 'material'], moods: ['sereno', 'sofisticado'], palettes: [['marfim, carvão e bronze', 'alto contraste contido', 'bronze apenas nos detalhes'], ['pedra quente, preto e champanhe', 'contraste editorial', 'champanhe em CTA e metadados']], typography: [['Cormorant Garamond', 'Manrope', 'headlines monumentais com tracking apertado'], ['DM Serif Display', 'Inter', 'títulos amplos e navegação discreta']], heroes: ['EDITORIAL_FULL_BLEED', 'ARCHITECTURAL_EDITORIAL', 'TYPOGRAPHY_OVER_IMAGE'], image: ['arquitetura residencial contemporânea premium', 'wide architectural photography, 24mm lens', 'golden hour lateral light', 'edificação ocupando o lado direito da cena', '35% do quadro limpo à esquerda para headline'], composition: 'Imagem dominante, navegação mínima e uma peça de informação discreta no rodapé da hero.', decorative: 'Linhas finas, blocos de pedra e tipografia em grande escala; nenhum ornamento gratuito.', rhythm: 'Sequência editorial: imagem ampla, informação curta, prova de confiança e localização.', interaction: 'Transições lentas e táteis; hover discreto em imagens e links.' },
  standard_real_estate: { secondary: 'property_search', personality: ['gráfico', 'confiante', 'contemporâneo'], keywords: ['editorial-grid', 'large-type', 'architecture', 'curated'], moods: ['ambicioso', 'claro'], palettes: [['off-white, grafite e verde mineral', 'alto contraste', 'verde reservado para ação'], ['cinza concreto, azul profundo e cobre', 'contraste sóbrio', 'cobre para dados']], typography: [['DM Serif Display', 'Manrope', 'marca grande e leitura funcional'], ['Playfair Display', 'Inter', 'headline editorial e dados compactos']], heroes: ['GIANT_BRAND_WORD', 'MAGAZINE_LAYOUT', 'ARCHITECTURAL_EDITORIAL'], image: ['arquitetura contemporânea e interiores bem iluminados', 'architectural editorial, 28mm lens', 'luz natural de fim de tarde', 'edificação recortada sobre tipografia monumental', 'faixa limpa para busca ou CTA'], composition: 'Grid editorial com marca grande, arquitetura sobreposta e dados seletivos.', decorative: 'Lettering ampliado, grades finas e recortes arquitetônicos.', rhythm: 'Alternar galeria, dados e narrativa sem empilhar cartões idênticos.', interaction: 'Movimento curto em galerias e realce de links.' },
  burger_restaurant: { secondary: 'food_campaign', personality: ['ousado', 'apetitoso', 'energético'], keywords: ['macro-food', 'campaign', 'texture', 'bold-type'], moods: ['desejo', 'energia'], palettes: [['vermelho tomate, creme e carvão', 'contraste alto', 'vermelho como chamada principal'], ['amarelo mostarda, preto e branco', 'contraste gráfico', 'amarelo em selos pontuais']], typography: [['Bebas Neue', 'Manrope', 'headline condensada e monumental'], ['Archivo Black', 'Inter', 'títulos publicitários e texto limpo']], heroes: ['PRODUCT_MONUMENT', 'PRODUCT_CAMPAIGN', 'LAYERED_COLLAGE'], image: ['hambúrguer artesanal em close com textura e ingredientes', 'macro commercial food photography, 85mm lens', 'luz dramática lateral', 'produto dominando o centro ou lado direito', 'área escura ou limpa para texto grande'], composition: 'Produto em primeiro plano, headline de campanha e apenas um CTA inequívoco.', decorative: 'Selos gráficos, formas recortadas e textura controlada; sem widgets de SaaS.', rhythm: 'Produto, atmosfera, prova real e chamada direta.', interaction: 'Micro zoom em comida e botão com resposta tátil.' },
  pizza_restaurant: { secondary: 'food_campaign', personality: ['expressivo', 'quente', 'autêntico'], keywords: ['food-editorial', 'italian', 'craft', 'warm'], moods: ['acolhimento', 'apetite'], palettes: [['tomate, creme e verde oliva', 'contraste quente', 'vermelho em CTA'], ['vinho, bege e preto', 'contraste dramático', 'bege para respiro']], typography: [['Fraunces', 'Manrope', 'serif expressiva com suporte limpo'], ['DM Serif Display', 'Inter', 'títulos de menu editorial']], heroes: ['PRODUCT_CAMPAIGN', 'EDITORIAL_FULL_BLEED', 'MAGAZINE_LAYOUT'], image: ['pizza artesanal recém-assada com textura visível', 'commercial food photography, top three-quarter angle', 'luz quente e dramática', 'produto amplo com recorte editorial', 'margem limpa para headline'], composition: 'Produto forte e narrativa de hospitalidade, sem grade automática de serviços.', decorative: 'Arcos, linhas finas e marcas gráficas orgânicas.', rhythm: 'Imagem, detalhe, ambiente, localização e CTA.', interaction: 'Leve deslocamento de imagem e transições de menu.' },
  sushi_restaurant: { secondary: 'premium_food', personality: ['preciso', 'dramático', 'refinado'], keywords: ['dark-food', 'japanese-inspired', 'precision', 'negative-space'], moods: ['ritual', 'sofisticação'], palettes: [['preto, creme e vermelho laca', 'contraste alto', 'vermelho apenas em gestos'], ['verde profundo, areia e cobre', 'contraste elegante', 'cobre em detalhes']], typography: [['Cormorant Garamond', 'Manrope', 'serif refinada com texto preciso'], ['Bodoni Moda', 'Inter', 'grande contraste em títulos']], heroes: ['TYPOGRAPHY_OVER_IMAGE', 'EDITORIAL_FULL_BLEED', 'ASYMMETRIC_SHOWCASE'], image: ['sushi premium em apresentação minimalista', 'dramatic commercial food photography, 85mm lens', 'luz direcional baixa', 'prato no lado direito com fundo escuro', 'espaço negativo escuro à esquerda'], composition: 'Assimetria com produto iluminado e tipografia silenciosa.', decorative: 'Linhas, círculos e módulos inspirados em papel; sem clichês literais.', rhythm: 'Ritual visual alternando close, respiro e informação.', interaction: 'Revelações contidas e hover em pratos.' },
  premium_restaurant: { secondary: 'hospitality', personality: ['sensorial', 'acolhedor', 'editorial'], keywords: ['hospitality', 'warm-light', 'editorial', 'atmosphere'], moods: ['desejo', 'acolhimento'], palettes: [['creme, vinho profundo e açafrão', 'contraste caloroso', 'vinho para ação'], ['papel quente, oliva e terracota', 'contraste suave', 'terracota como assinatura']], typography: [['Fraunces', 'Manrope', 'voz editorial e corpo neutro'], ['DM Serif Display', 'Inter', 'hospitalidade sofisticada']], heroes: ['CINEMATIC_SPLIT', 'MAGAZINE_LAYOUT', 'EDITORIAL_FULL_BLEED'], image: ['ambiente gastronômico contemporâneo e acolhedor', 'editorial hospitality photography, 35mm lens', 'luz quente de fim de tarde', 'mesa ou ambiente ocupando dois terços do quadro', 'respiro para texto e CTA'], composition: 'Narrativa de experiência antes de fichas ou cartões.', decorative: 'Bordas sutis, texturas de papel e recortes de foto.', rhythm: 'Alternar sala, prato, reputação e visita.', interaction: 'Movimento suave de imagem e CTA tátil.' },
  acai_brand: { secondary: 'food_campaign', personality: ['vibrante', 'jovem', 'monumental'], keywords: ['purple', 'fruit', 'energy', 'product-shot'], moods: ['energia', 'frescor'], palettes: [['roxo intenso, magenta e preto', 'contraste vibrante', 'magenta para movimento'], ['açaí, lilás e creme', 'contraste limpo', 'roxo em pontos focais']], typography: [['Archivo Black', 'Manrope', 'headline grande de campanha'], ['Anton', 'Inter', 'tipografia condensada e direta']], heroes: ['PRODUCT_MONUMENT', 'GIANT_BRAND_WORD', 'LAYERED_COLLAGE'], image: ['tigela de açaí premium com frutas e textura', 'high-end commercial food photography, 50mm lens', 'luz de estúdio vibrante', 'produto central grande com frutas em movimento controlado', 'área lateral limpa para copy'], composition: 'Produto monumental, tipografia atrás do produto e uma ação direta.', decorative: 'Splash abstrato e formas de fruta sem poluir.', rhythm: 'Campanha visual, detalhes, prova e CTA.', interaction: 'Hover energético mas curto; reduced motion obrigatório.' },
  solar_energy: { secondary: 'premium_home', personality: ['otimista', 'tecnológico', 'confiável'], keywords: ['clean-energy', 'architecture', 'data', 'sunlight'], moods: ['progresso', 'segurança'], palettes: [['azul céu, verde profundo e amarelo solar', 'contraste claro', 'amarelo apenas em destaque'], ['navy, branco e verde energia', 'contraste técnico', 'verde para CTA']], typography: [['Space Grotesk', 'Manrope', 'headline técnica, humana e ampla'], ['Sora', 'Inter', 'dados claros e títulos fortes']], heroes: ['FLOATING_DATA', 'CINEMATIC_SPLIT', 'ARCHITECTURAL_EDITORIAL'], image: ['residência contemporânea com painéis solares', 'commercial architectural photography, 24mm lens', 'luz solar limpa e céu profundo', 'casa e placas no lado direito com paisagem', 'céu limpo à esquerda para headline'], composition: 'Arquitetura e energia como protagonista; dados pequenos flutuam apenas se confirmados ou genéricos.', decorative: 'Linhas de energia, grids solares e transparências discretas.', rhythm: 'Hero visual, contexto, processo, confiança e contato.', interaction: 'Dados surgem de forma breve; sem efeitos chamativos.' },
  electronic_security: { secondary: 'technology', personality: ['protetor', 'técnico', 'preciso'], keywords: ['dark-tech', 'security', 'cyan', 'operations'], moods: ['controle', 'confiança'], palettes: [['navy, preto, cyan e branco', 'alto contraste', 'cyan em indicadores seletivos'], ['grafite, azul elétrico e cinza gelo', 'contraste corporativo', 'azul em CTA']], typography: [['Space Grotesk', 'Inter', 'títulos técnicos e leitura direta'], ['Sora', 'Manrope', 'clareza operacional']], heroes: ['DARK_TECH', 'FLOATING_DATA', 'ASYMMETRIC_SHOWCASE'], image: ['instalação profissional de segurança eletrônica em contexto corporativo', 'cinematic commercial photography, 35mm lens', 'luz azul profunda e pontos de contraste', 'técnico ou equipamento no lado direito', 'área escura limpa para mensagem curta'], composition: 'Cena operacional escura, headline curta e indicadores que não fingem dados da empresa.', decorative: 'Linhas de sinal, grade técnica e brilho contido.', rhythm: 'Proteção, contexto, confiança, localização e CTA.', interaction: 'Micro feedback técnico e transições rápidas.' },
  transport_logistics: { secondary: 'industrial', personality: ['dinâmico', 'robusto', 'confiável'], keywords: ['cinematic-road', 'fleet', 'motion', 'scale'], moods: ['movimento', 'escala'], palettes: [['azul noite, laranja e branco', 'alto contraste', 'laranja como sinal de ação'], ['grafite, vermelho profundo e aço', 'contraste industrial', 'vermelho em chamada']], typography: [['Archivo Narrow', 'Manrope', 'headline robusta e comprimida'], ['Barlow Condensed', 'Inter', 'ritmo de transporte']], heroes: ['EDITORIAL_FULL_BLEED', 'DARK_TECH', 'GIANT_BRAND_WORD'], image: ['caminhão ou frota em estrada cinematográfica', 'cinematic transport photography, 35mm lens', 'luz de fim de tarde ou noturna', 'veículo avançando no lado direito com sensação de movimento', 'faixa escura livre para headline'], composition: 'Escala e movimento, sem tabela burocrática como hero.', decorative: 'Faixas de rota, números grandes e linhas de velocidade contidas.', rhythm: 'Cena, capacidade, confiança e contato.', interaction: 'Movimento quase imperceptível na mídia e CTA firme.' },
  veterinary: { secondary: 'care', personality: ['humano', 'calmo', 'acolhedor'], keywords: ['animal-care', 'organic', 'trust', 'warm'], moods: ['cuidado', 'confiança'], palettes: [['verde floresta, creme e areia', 'contraste natural', 'verde para CTA'], ['azul suave, off-white e terracota', 'contraste gentil', 'terracota em detalhes']], typography: [['Newsreader', 'Manrope', 'serif humana e leitura tranquila'], ['Instrument Serif', 'Inter', 'calma e precisão']], heroes: ['ORGANIC_CARE', 'CINEMATIC_SPLIT', 'ASYMMETRIC_SHOWCASE'], image: ['veterinário ou tutor com animal em contexto de cuidado', 'emotional commercial photography, 50mm lens', 'luz natural suave', 'pessoa e animal no lado direito', 'espaço claro e calmo para texto'], composition: 'Cena emocional, formas orgânicas moderadas e acesso claro ao contato.', decorative: 'Curvas sutis e recortes naturais; nunca infantilizar.', rhythm: 'Cuidado, ambiente, confiança, localização e CTA.', interaction: 'Revelação suave, sem animações brincalhonas.' },
  pet_store: { secondary: 'retail', personality: ['vibrante', 'amigável', 'expressivo'], keywords: ['pet', 'playful', 'color', 'expressive'], moods: ['alegria', 'proximidade'], palettes: [['azul, laranja e creme', 'contraste alto', 'laranja para CTA'], ['verde menta, amarelo e grafite', 'contraste alegre', 'amarelo em acentos']], typography: [['Baloo 2', 'Manrope', 'display amigável mas legível'], ['Fredoka', 'Inter', 'personalidade e corpo neutro']], heroes: ['ORGANIC_CARE', 'LAYERED_COLLAGE', 'PRODUCT_CAMPAIGN'], image: ['animal expressivo em ambiente claro e premium', 'commercial pet photography, 50mm lens', 'luz suave e cores vivas', 'animal em recorte protagonista', 'espaço limpo para headline'], composition: 'Imagem expressiva e blocos gráficos com poucos elementos.', decorative: 'Formas orgânicas e pequenos acentos, sem excesso de stickers.', rhythm: 'Protagonista, seleção, confiança e visita.', interaction: 'Hover leve e movimentos curtos.' },
  beauty: { secondary: 'premium_service', personality: ['refinado', 'sensorial', 'moderno'], keywords: ['editorial', 'beauty', 'soft-light', 'refined'], moods: ['refinamento', 'autoconfiança'], palettes: [['areia, rosa queimado e grafite', 'contraste elegante', 'rosa em acentos'], ['creme, preto e cobre', 'contraste editorial', 'cobre em detalhes']], typography: [['Cormorant Garamond', 'Manrope', 'contraste editorial e leitura limpa'], ['Bodoni Moda', 'Inter', 'luxo contemporâneo']], heroes: ['EDITORIAL_FULL_BLEED', 'MAGAZINE_LAYOUT', 'MINIMAL_PRODUCT'], image: ['detalhe de beleza ou ambiente sofisticado com materiais táteis', 'beauty editorial photography, 85mm lens', 'luz macia e direcional', 'sujeito posicionado lateralmente', 'espaço negativo para tipografia'], composition: 'Editorial de revista com uma ação de contato clara.', decorative: 'Linhas, formas suaves e muito respiro.', rhythm: 'Detalhe, atmosfera, informação e CTA.', interaction: 'Transições elegantes e lentas.' },
  clinic: { secondary: 'care', personality: ['claro', 'sereno', 'competente'], keywords: ['healthcare', 'calm', 'clean', 'trust'], moods: ['confiança', 'clareza'], palettes: [['branco mineral, azul petróleo e sálvia', 'contraste profissional', 'sálvia em detalhes'], ['névoa, grafite e verde suave', 'contraste baixo controlado', 'verde em CTA']], typography: [['Instrument Serif', 'Manrope', 'calma editorial e boa leitura'], ['Newsreader', 'Inter', 'humanidade e precisão']], heroes: ['ORGANIC_CARE', 'MINIMAL_PRODUCT', 'CINEMATIC_SPLIT'], image: ['interior de clínica moderno e acolhedor', 'clean commercial interior photography, 28mm lens', 'luz natural suave', 'ambiente no lado direito', 'parede clara limpa para mensagem'], composition: 'Clareza e acolhimento antes de qualquer lista de procedimentos.', decorative: 'Curvas muito sutis, espaços claros e detalhes naturais.', rhythm: 'Confiança, ambiente, localização e contato.', interaction: 'Movimento discreto, foco em legibilidade.' },
  dentist: { secondary: 'care', personality: ['preciso', 'calmo', 'confiável'], keywords: ['dental', 'clean', 'clinical', 'trust'], moods: ['segurança', 'cuidado'], palettes: [['branco, azul profundo e sálvia', 'contraste claro', 'azul em ação'], ['gelo, grafite e verde água', 'contraste limpo', 'verde água em acentos']], typography: [['Sora', 'Manrope', 'clareza contemporânea'], ['Newsreader', 'Inter', 'voz humana e clínica']], heroes: ['CINEMATIC_SPLIT', 'ORGANIC_CARE', 'MINIMAL_PRODUCT'], image: ['clínica odontológica contemporânea e luminosa', 'clean healthcare photography, 28mm lens', 'luz suave natural', 'ambiente no lado direito sem pessoas olhando para câmera', 'parede clara livre para texto'], composition: 'Hero limpo e confiança imediata sem inventar procedimentos.', decorative: 'Linhas delicadas e superfícies claras.', rhythm: 'Ambiente, confiança verificada, localização e contato.', interaction: 'Feedbacks claros e poucas transições.' },
  law_firm: { secondary: 'professional_service', personality: ['institucional', 'sereno', 'autoridade'], keywords: ['editorial', 'institutional', 'quiet-confidence', 'architecture'], moods: ['autoridade', 'clareza'], palettes: [['marfim, azul tinta e cobre', 'contraste institucional', 'cobre em detalhes'], ['papel, grafite e verde escuro', 'contraste sóbrio', 'verde em CTA']], typography: [['Cormorant Garamond', 'Manrope', 'autoridade editorial'], ['DM Serif Display', 'Inter', 'institucional e legível']], heroes: ['TYPOGRAPHY_OVER_IMAGE', 'MAGAZINE_LAYOUT', 'MINIMAL_PRODUCT'], image: ['arquitetura institucional ou escritório sofisticado sem pessoas posadas', 'editorial architectural photography, 35mm lens', 'luz lateral refinada', 'estrutura no lado direito', 'espaço negativo para título'], composition: 'Tipografia e estrutura arquitetônica em vez de promessas exageradas.', decorative: 'Regras tipográficas, linhas finas e hierarquia firme.', rhythm: 'Tese, abordagem, confiança e contato.', interaction: 'Interações contidas e formais.' },
  accounting: { secondary: 'professional_service', personality: ['claro', 'confiável', 'organizado'], keywords: ['clarity', 'professional', 'structured', 'calm'], moods: ['segurança', 'clareza'], palettes: [['navy, gelo e verde profundo', 'contraste corporativo', 'verde como ação'], ['off-white, grafite e azul', 'contraste limpo', 'azul para sinais']], typography: [['Sora', 'Inter', 'legibilidade e precisão'], ['Manrope', 'Inter', 'organização visual']], heroes: ['FLOATING_DATA', 'MAGAZINE_LAYOUT', 'MINIMAL_PRODUCT'], image: ['ambiente profissional contemporâneo com materiais de trabalho', 'commercial office photography, 35mm lens', 'luz clara e natural', 'composição lateral equilibrada', 'área limpa para headline'], composition: 'Dados abstratos e clareza visual, sem dashboard falso.', decorative: 'Grades, linhas e pequenos marcadores.', rhythm: 'Clareza, contexto, prova e contato.', interaction: 'Feedback objetivo e curto.' },
  construction: { secondary: 'industrial', personality: ['robusto', 'material', 'confiável'], keywords: ['materials', 'craft', 'scale', 'structure'], moods: ['solidez', 'precisão'], palettes: [['cimento, carvão e laranja queimado', 'contraste forte', 'laranja em ação'], ['areia, preto e verde mineral', 'contraste material', 'verde em destaque']], typography: [['Archivo Narrow', 'Manrope', 'força e leitura'], ['Barlow Condensed', 'Inter', 'ritmo industrial']], heroes: ['ARCHITECTURAL_EDITORIAL', 'ASYMMETRIC_SHOWCASE', 'EDITORIAL_FULL_BLEED'], image: ['obra ou material de construção em fotografia editorial', 'commercial construction photography, 28mm lens', 'luz lateral com textura', 'estrutura no lado direito', 'espaço de respiro para texto'], composition: 'Matéria e escala antes de cartões de serviço.', decorative: 'Grades construtivas, linhas de medida e textura sutil.', rhythm: 'Material, processo, resultado e orçamento.', interaction: 'Hover de imagem e movimento reduzido.' },
  architecture: { secondary: 'premium_service', personality: ['minimalista', 'autoral', 'espacial'], keywords: ['architecture', 'negative-space', 'materials', 'editorial'], moods: ['contemplação', 'precisão'], palettes: [['papel, grafite e verde mineral', 'contraste editorial', 'verde em acentos'], ['branco, preto e terracota', 'contraste arquitetônico', 'terracota pontual']], typography: [['DM Serif Display', 'Manrope', 'título espacial e texto contido'], ['Cormorant Garamond', 'Inter', 'luxo arquitetônico']], heroes: ['ARCHITECTURAL_EDITORIAL', 'GIANT_BRAND_WORD', 'MAGAZINE_LAYOUT'], image: ['arquitetura contemporânea com geometria forte', 'architectural editorial photography, 24mm lens', 'luz de fim de tarde', 'volume arquitetônico recortado', 'céu ou parede limpa para tipografia'], composition: 'Imagem e tipografia em diálogo, sem caixa de serviços repetida.', decorative: 'Grid, linhas de projeto e recortes estruturais.', rhythm: 'Espaço, materiais, narrativa e contato.', interaction: 'Transições contemplativas.' },
  automotive: { secondary: 'industrial', personality: ['potente', 'preciso', 'dinâmico'], keywords: ['automotive', 'motion', 'metal', 'contrast'], moods: ['energia', 'confiança'], palettes: [['preto, aço e vermelho', 'contraste intenso', 'vermelho em CTA'], ['grafite, azul elétrico e branco', 'contraste técnico', 'azul em detalhes']], typography: [['Archivo Narrow', 'Inter', 'headline robusta'], ['Barlow Condensed', 'Manrope', 'ritmo de performance']], heroes: ['DARK_TECH', 'CINEMATIC_SPLIT', 'PRODUCT_MONUMENT'], image: ['veículo ou detalhe automotivo premium em contexto', 'cinematic automotive photography, 50mm lens', 'luz especular e profunda', 'produto no lado direito', 'sombra limpa para texto'], composition: 'Produto ou movimento como protagonista, CTA direto.', decorative: 'Linhas aerodinâmicas e reflexos discretos.', rhythm: 'Impacto, capacidade, confiança e contato.', interaction: 'Hover com deslocamento mínimo.' },
  gym: { secondary: 'wellness', personality: ['enérgico', 'disciplinado', 'forte'], keywords: ['fitness', 'contrast', 'motion', 'strength'], moods: ['energia', 'foco'], palettes: [['preto, branco e verde ácido', 'contraste alto', 'verde só para ação'], ['grafite, areia e laranja', 'contraste robusto', 'laranja em marcadores']], typography: [['Archivo Black', 'Manrope', 'headline forte e direta'], ['Space Grotesk', 'Inter', 'dados claros']], heroes: ['DARK_TECH', 'PRODUCT_CAMPAIGN', 'GIANT_BRAND_WORD'], image: ['ambiente de treino premium com ação realista', 'commercial fitness photography, 35mm lens', 'luz contrastada e texturas reais', 'atleta ou equipamento no lado direito', 'espaço escuro para copy'], composition: 'Energia visual sem prometer resultados não confirmados.', decorative: 'Tipografia grande e marcas de movimento contidas.', rhythm: 'Impacto, ambiente, motivação e contato.', interaction: 'Reveals rápidos e reduzidos em mobile.' },
  hotel: { secondary: 'hospitality', personality: ['calmo', 'sofisticado', 'imersivo'], keywords: ['hospitality', 'architecture', 'warm', 'escape'], moods: ['descanso', 'desejo'], palettes: [['creme, verde profundo e cobre', 'contraste acolhedor', 'cobre em detalhes'], ['areia, azul noite e branco', 'contraste sereno', 'azul em ação']], typography: [['Cormorant Garamond', 'Manrope', 'hospitalidade editorial'], ['Fraunces', 'Inter', 'calor e leitura']], heroes: ['EDITORIAL_FULL_BLEED', 'ARCHITECTURAL_EDITORIAL', 'MAGAZINE_LAYOUT'], image: ['hotel ou hospedagem de arquitetura acolhedora', 'hospitality editorial photography, 24mm lens', 'luz dourada suave', 'ambiente ocupando maior parte do quadro', 'respiro no céu ou parede para headline'], composition: 'Imagem imersiva e informação de reserva sem exagero.', decorative: 'Linhas e tipografia espaçada.', rhythm: 'Chegada, ambiente, confiança, localização e contato.', interaction: 'Movimento calmo e legível.' },
  tourism: { secondary: 'experience', personality: ['imersivo', 'curioso', 'luminoso'], keywords: ['travel', 'landscape', 'editorial', 'adventure'], moods: ['descoberta', 'liberdade'], palettes: [['azul profundo, areia e coral', 'contraste vibrante', 'coral em CTA'], ['verde floresta, creme e laranja', 'contraste natural', 'laranja como ação']], typography: [['DM Serif Display', 'Manrope', 'narrativa de viagem'], ['Fraunces', 'Inter', 'editorial e claro']], heroes: ['EDITORIAL_FULL_BLEED', 'LAYERED_COLLAGE', 'MAGAZINE_LAYOUT'], image: ['paisagem ou experiência turística cinematográfica', 'cinematic travel photography, 24mm lens', 'luz de amanhecer ou pôr do sol', 'paisagem ampla com elemento humano pequeno', 'céu ou água limpa para texto'], composition: 'Fotografia como porta de entrada e CTA de descoberta.', decorative: 'Mapas abstratos e linhas de rota discretas.', rhythm: 'Imersão, informações, localização e contato.', interaction: 'Reveals lentos e sem parallax agressivo.' },
  saas: { secondary: 'technology', personality: ['preciso', 'ambicioso', 'moderno'], keywords: ['dark-tech', 'product', 'data', 'clarity'], moods: ['progresso', 'controle'], palettes: [['navy, preto e azul elétrico', 'alto contraste', 'azul em CTA'], ['grafite, branco e verde ácido', 'contraste técnico', 'verde em ação']], typography: [['Space Grotesk', 'Inter', 'tecnologia e clareza'], ['Sora', 'Manrope', 'produto premium']], heroes: ['DARK_TECH', 'FLOATING_DATA', 'MINIMAL_PRODUCT'], image: ['produto tecnológico abstrato ou ambiente de trabalho sofisticado', 'premium technology editorial photography, 50mm lens', 'luz de estúdio controlada', 'objeto ou composição no lado direito', 'fundo limpo para headline'], composition: 'Tipografia forte e um único fragmento de produto, sem dashboard inventado.', decorative: 'Glow sutil, grids e dados abstratos.', rhythm: 'Proposta, contexto, confiança e ação.', interaction: 'Microinterações precisas e discretas.' },
  consulting: { secondary: 'professional_service', personality: ['estratégico', 'claro', 'premium'], keywords: ['editorial', 'strategy', 'clarity', 'confidence'], moods: ['clareza', 'autoridade'], palettes: [['preto, osso e azul elétrico', 'contraste alto', 'azul em CTA'], ['papel, grafite e cobre', 'contraste editorial', 'cobre como assinatura']], typography: [['DM Serif Display', 'Manrope', 'autoridade editorial'], ['Sora', 'Inter', 'clareza contemporânea']], heroes: ['MAGAZINE_LAYOUT', 'GIANT_BRAND_WORD', 'FLOATING_DATA'], image: ['ambiente de consultoria ou abstração arquitetônica premium', 'editorial commercial photography, 35mm lens', 'luz lateral refinada', 'composição assimétrica', 'espaço negativo para título'], composition: 'Pensamento e hierarquia, não um conjunto de dashboards genéricos.', decorative: 'Regras, números grandes e blocos editoriais.', rhythm: 'Tese, método, confiança e contato.', interaction: 'Transições formais e curtas.' },
  industrial: { secondary: 'technical_service', personality: ['técnico', 'material', 'direto'], keywords: ['industrial', 'precision', 'materials', 'scale'], moods: ['robustez', 'confiança'], palettes: [['grafite, aço e verde industrial', 'contraste forte', 'verde em CTA'], ['cinza concreto, preto e cobre', 'contraste material', 'cobre em detalhes']], typography: [['Archivo Narrow', 'Manrope', 'força industrial'], ['Barlow Condensed', 'Inter', 'clareza técnica']], heroes: ['ASYMMETRIC_SHOWCASE', 'DARK_TECH', 'ARCHITECTURAL_EDITORIAL'], image: ['processo industrial ou material em detalhe', 'commercial industrial photography, 35mm lens', 'luz lateral com textura', 'máquina ou material no lado direito', 'área limpa para headline'], composition: 'Matéria e processo apresentados com respiro editorial.', decorative: 'Grades, linhas de medida e textura discreta.', rhythm: 'Capacidade, materiais, confiança e contato.', interaction: 'Hover técnico mínimo.' },
  retail: { secondary: 'local_commerce', personality: ['direto', 'acolhedor', 'visual'], keywords: ['retail', 'local', 'curated', 'clear'], moods: ['proximidade', 'desejo'], palettes: [['creme, grafite e verde profundo', 'contraste claro', 'verde em CTA'], ['branco, azul e terracota', 'contraste amigável', 'terracota em destaques']], typography: [['Fraunces', 'Manrope', 'personalidade local'], ['Sora', 'Inter', 'clareza comercial']], heroes: ['CINEMATIC_SPLIT', 'MAGAZINE_LAYOUT', 'ASYMMETRIC_SHOWCASE'], image: ['produto ou ambiente de comércio local bem curado', 'commercial lifestyle photography, 50mm lens', 'luz natural rica', 'produto no lado direito', 'espaço limpo para texto'], composition: 'Produto ou ambiente, narrativa curta e acesso ao contato.', decorative: 'Recortes e tipografia simples.', rhythm: 'Destaque, ambiente, prova e visita.', interaction: 'Detalhes de hover suaves.' },
  generic_local_service: { secondary: 'local_service', personality: ['confiável', 'claro', 'contemporâneo'], keywords: ['local-business', 'trust', 'clean', 'editorial'], moods: ['confiança', 'clareza'], palettes: [['off-white, grafite e verde profundo', 'contraste alto', 'verde em CTA'], ['papel, azul tinta e cobre', 'contraste editorial', 'cobre em detalhes']], typography: [['DM Serif Display', 'Manrope', 'personalidade editorial e leitura'], ['Sora', 'Inter', 'clareza contemporânea']], heroes: ['ASYMMETRIC_SHOWCASE', 'MAGAZINE_LAYOUT', 'CINEMATIC_SPLIT'], image: ['negócio local em contexto profissional e bem iluminado', 'commercial editorial photography, 35mm lens', 'luz natural lateral', 'assunto posicionado lateralmente', 'espaço limpo para headline'], composition: 'Direção editorial com um protagonista visual e contato objetivo.', decorative: 'Linhas finas e ritmo de espaços.', rhythm: 'Contexto, confiança, localização e ação.', interaction: 'Transições curtas e acessíveis.' },
};

// Reuse the nearest grammar for services whose visual language is related.
grammars.acai_brand = grammars.acai_brand;
grammars.construction = grammars.construction;

function hash(seed: string): number {
  let value = 2166136261;
  for (const character of seed) value = Math.imul(value ^ character.charCodeAt(0), 16777619);
  return value >>> 0;
}

function pick<T>(items: readonly T[], seed: number, offset: number): T { return items[(seed + offset) % items.length]; }
function businessText(context: WebsiteGenerationContext): string {
  const business = context.business;
  return [business.name, business.category, ...business.categories, context.summary, context.notes].join(' ').toLocaleLowerCase('pt-BR');
}

export function classifyVisualNiche(context: WebsiteGenerationContext): { primaryArchetype: VisualArchetype; secondaryArchetype: string; signals: string[] } {
  const source = businessText(context);
  const choose = (primaryArchetype: VisualArchetype, secondaryArchetype: string, signal: string) => ({ primaryArchetype, secondaryArchetype, signals: [signal] });
  if (/imobili|imovel|imóveis|real estate|corretor/.test(source)) return /luxo|premium|alto padr[aã]o|condom[ií]nio/.test(source) ? choose('luxury_real_estate', 'premium_home', 'imobiliário com sinal de posicionamento premium') : choose('standard_real_estate', 'property_search', 'imobiliário ou corretagem');
  if (/hamburg|burger/.test(source)) return choose('burger_restaurant', 'food_campaign', 'hambúrguer ou burger');
  if (/pizz/.test(source)) return choose('pizza_restaurant', 'food_campaign', 'pizza');
  if (/sushi|japon[eê]s|temaki/.test(source)) return choose('sushi_restaurant', 'premium_food', 'gastronomia japonesa');
  if (/a[cç]a[ií]/.test(source)) return choose('acai_brand', 'food_campaign', 'açaí');
  if (/restaurante|churrasc|bar|cafe|caf[eé]|padaria|confeit|aliment/.test(source)) return choose('premium_restaurant', 'hospitality', 'alimentação ou hospitalidade');
  if (/solar|fotovoltaic|energia/.test(source)) return choose('solar_energy', 'premium_home', 'energia solar');
  if (/seguran[cç]|c[aâ]mera|monitoramento|alarme|controle de acesso/.test(source)) return choose('electronic_security', 'technology', 'segurança eletrônica');
  if (/transport|log[ií]st|frete|carga|frota|mudan[cç]/.test(source)) return choose('transport_logistics', 'industrial', 'transporte ou logística');
  if (/veterin|cl[ií]nica vet/.test(source)) return choose('veterinary', 'care', 'veterinária');
  if (/pet shop|petshop|ra[cç][aã]o/.test(source)) return choose('pet_store', 'retail', 'pet shop');
  if (/barbear|sal[aã]o|beleza|est[eé]tica|cabel/.test(source)) return choose('beauty', 'premium_service', 'beleza ou estética');
  if (/dent/.test(source)) return choose('dentist', 'care', 'odontologia');
  if (/cl[ií]nica|m[eé]dic|sa[uú]de/.test(source)) return choose('clinic', 'care', 'saúde ou clínica');
  if (/advog|jur[ií]d|law/.test(source)) return choose('law_firm', 'professional_service', 'advocacia');
  if (/cont[aá]bil|contabil|contador/.test(source)) return choose('accounting', 'professional_service', 'contabilidade');
  if (/arquitet/.test(source)) return choose('architecture', 'premium_service', 'arquitetura');
  if (/constru|marmor|granito|obra|engenh/.test(source)) return choose('construction', 'industrial', 'construção ou materiais');
  if (/oficina|auto|mec[aâ]nic|ve[ií]cul/.test(source)) return choose('automotive', 'industrial', 'automotivo');
  if (/academia|gym|fitness|treino/.test(source)) return choose('gym', 'wellness', 'academia ou fitness');
  if (/hotel|pousada|hosped/.test(source)) return choose('hotel', 'hospitality', 'hospedagem');
  if (/turismo|viagem|tour/.test(source)) return choose('tourism', 'experience', 'turismo');
  if (/software|saas|tecnologia|sistema/.test(source)) return choose('saas', 'technology', 'software ou tecnologia');
  if (/consult|assessoria/.test(source)) return choose('consulting', 'professional_service', 'consultoria');
  if (/industri|metal|m[aá]quina|fabrica/.test(source)) return choose('industrial', 'technical_service', 'indústria');
  if (/loja|varejo|moda|com[eé]rcio/.test(source)) return choose('retail', 'local_commerce', 'varejo');
  return choose('generic_local_service', 'local_service', 'serviço local sem classificação específica');
}

export function createArtDirectionPlan(context: WebsiteGenerationContext, analysis: BusinessAnalysis): ArtDirectionPlan {
  const classified = classifyVisualNiche(context);
  const grammar = grammars[classified.primaryArchetype];
  const seedKey = `${context.business.googlePlaceId || context.business.name}|${classified.primaryArchetype}`;
  const seed = hash(seedKey);
  const palette = pick(grammar.palettes, seed, 1);
  const type = pick(grammar.typography, seed, 2);
  const hero = pick(grammar.heroes, seed, 3);
  const [subject, camera, lighting, composition, negativeSpace] = grammar.image;
  const businessType = context.business.category || context.business.categories[0] || 'negócio local';
  return artDirectionPlanSchema.parse({
    version: 'art-direction-v1', seed: seedKey, businessType,
    primaryArchetype: classified.primaryArchetype, secondaryArchetype: classified.secondaryArchetype,
    classificationSignals: classified.signals,
    businessPositioning: analysis.positioning,
    targetAudience: analysis.audience,
    visualPersonality: grammar.personality,
    visualKeywords: grammar.keywords,
    primaryMood: grammar.moods[0], secondaryMood: grammar.moods[1],
    colorStrategy: { paletteFamily: palette[0], contrast: palette[1], accentUse: palette[2] },
    typographyStrategy: { display: type[0], body: type[1], scale: type[2], rationale: 'A combinação é escolhida pela personalidade visual do arquétipo, com leitura preservada no mobile.' },
    imageDirection: { subject, camera, lighting, composition, negativeSpace, palette: palette[0], avoid: ['texto dentro da imagem', 'logos ou marcas de terceiros', 'watermarks', 'pessoas posadas olhando para a câmera sem contexto', 'HDR artificial', 'arquitetura ou objetos deformados'] },
    hero: { archetype: hero, concept: `${grammar.moods[0]} através de ${grammar.keywords.slice(0, 3).join(', ')}.`, composition: grammar.composition, dominantElement: subject, textPlacement: negativeSpace, supportingElements: ['um CTA principal real', 'prova social somente quando verificada', 'detalhes de conversão discretos'] },
    contentHierarchy: ['Hero com uma ideia dominante', 'Contexto ou experiência em composição editorial', 'Prova de confiança usando somente fatos disponíveis', 'Localização e canal de contato verificáveis', 'CTA final com a mesma linguagem visual'],
    decorativeLanguage: grammar.decorative,
    sectionRhythm: grammar.rhythm,
    interactionStyle: grammar.interaction,
    mobileStrategy: 'Recompor a hero em uma coluna, preservar o protagonista visual, reduzir sobreposições e garantir que headline e CTA não dependam de scale() ou de um crop desktop.',
    conversionStrategy: analysis.primaryGoal,
    qualityTargets: { visualImpact: 8.5, heroQuality: 9, imageQuality: 8.5, responsiveQuality: 8.5 },
  });
}

export function artDirectionPromptBlock(plan: ArtDirectionPlan): string {
  return `LOCKED ART_DIRECTION_PLAN (created before code; execute this plan without inventing business facts):\n${JSON.stringify(plan, null, 2)}`;
}

export function visualSkillFiles(plan: ArtDirectionPlan): string[] {
  const files = ['art-director.md', 'visual-composition.md', 'image-director.md', 'visual-critic.md'];
  const nicheMap: Partial<Record<VisualArchetype, string>> = {
    luxury_real_estate: 'niches/real-estate.md', standard_real_estate: 'niches/real-estate.md', solar_energy: 'niches/solar.md',
    electronic_security: 'niches/security.md', transport_logistics: 'niches/logistics.md', burger_restaurant: 'niches/burger.md',
    pizza_restaurant: 'niches/pizza.md', sushi_restaurant: 'niches/sushi.md', acai_brand: 'niches/acai.md',
    veterinary: 'niches/veterinary.md', pet_store: 'niches/pet.md', consulting: 'niches/consulting.md', saas: 'niches/technology.md',
  };
  const niche = nicheMap[plan.primaryArchetype];
  if (niche) files.push(niche);
  return files;
}
